
mysql:
  database: aggregate_pay_transaction



swagger:
  enabled: true
  docket:
    aggregate_pay:
      title: 交易服务
      base-package: mao.aggregate_pay_transaction_service


authentication:
  user:
    header-name: token
    expire: 43200               # 外部token有效期为12小时
    pri-key: client/pri.key    # 加密
    pub-key: client/pub.key    # 解密


#HTTP格式配置
spring:
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
    messages:
      encoding: UTF‐8


      
      
#tomcat头信息(用户ip和访问协议)及访问路径配置
server:
  tomcat:
    remote_ip_header: x‐forwarded‐for
    protocol_header: x‐forwarded‐proto
  servlet:
    context‐path: /
  use‐forward‐headers: true



alipay:
  charSet: "UTF-8"
  serverUrl: "https://openapi.alipaydev.com/gateway.do"
  encryptionMethod: "RSA2"
  appId: xxxxxx
  appPrivateKey: "xxxxxxxxxEXQA/i3gQpdqIAwUSoXooE72qWQkUTojhbaswRpDQHscOFnJliGJA0DJkTdBae+w785icvMa+4usCsRYKJOFxX7pV0/YM3We3KS2bpXwyHswRwnlc7+VpBolCT8SxSbJ+zCnLGvXWc/QWYikt1e1ZJgKxgM+V/uD57veAHNnE0yfpH1HEXvfd8LAgZCjc8BRj0qS1KekcopvKH8uThwQ3a1/++JWZJIpK87XFUxTY42K+I1CgCHORBbjgXDvTb7IShdlSZGxg56gFTZBxR4nTYyR5EIB3S80BE5BD9jB5si1noonjKTnnnA+83v7tBt6nGCpgdKdOWvAka3AgMBAAECggEAQrazsVJKkq5x936pBHuCgThcW0m2y36KtE3Msg2S9PmYgMLHiDWoz+fIBaMldqJtd9W/XEIFwj2gWbx+8B/3FBR0pEW13xCCWy4I3hsFj4KOEk28G8EDlpGd70W+dZC4Y5zyF4o9RXsdkKDI7bj2kD4JUqwHdLTR/p/lWRbod3+TUx9Ee0pRegymeQFABe2W9f0M55feYhQTnTh2+bAhd0ku8kocGQqpGAkIpzOxkcQY7MRYxZLV2I3TLee5HePVaosuowhKT7gMF4iiwKFgLGeDXxTzglTtatcfgRIbbfiKDYd/CGm9YdIcU0rNWF91z7sfymeQpwOZo3Iog+jyyQKBgQDeQ6zmDkni5y0kuH9EboGtCsJEsP0HTDHElZFU9PZlPHgQwFgGeV7rQgxvXCBB3j6mR47Q+WDQaWHN30T2hbNcapvQbJxc2UydIuDSOAIaCH+rnCES28zf3G503Apc48f81OS6ilzoe0qIzsV9X5fJI6E7xeBT7cg6kd/bg7GGrQKBgQDBEdXPSnTEXl2FkKBQC9+6466T6n+pzP910a9HC6i2euqOe6U4Kcv0id07GvUnFcj8AACe7hoTIGRAopDuhr9GcMS8swVRE6UZ5LDPxh5PuOhh24KUoKVFb26xuwI3u6dCzMdjSmj24crBOO+h2Me0wZ2G8J3bhaak0EHtngHDcwKBgQC4XXab1hpfxtbhcNDQmMGkIhqHFDCuzvsxT8efqxp/WytU6deady7PApiB/u8a9BkPoKfMnC88cU2ZkawIuVrQO/ZHavBA7FbquTW36pGDuqz8UqP0mrJUtupAsQ0/hAotpQKd4YuzpCFtXebfWl3zkER76mVr+P9v5fTEh3bIeQKBgCNE4s4PR+1nX6Y6mU6GHMTDOu0CdXfLXw9i0qYj1xoesiJ9K91qpTtyw9s8PXR6YlDGn1ZpIJJF5Ip6KAeqzd5MU2Q1P89jy1FDmZkbFAZ0PN9DfkMwZYCdrpcBFpKf0Ro+1l2pBiuza5qIkB38v96hT+mKowurCpopASIrLx9JAoGAMW/lc2fIliD65H/wfAEcSgB2TjYu0v4VbF01eMwIw3clessrQoZ61yNHv5UljNI0hVJiNWs9X7iOApIBEzHRhAR9sK63d7yT+HdW/eZxRum+OpXPciJpL0IZ2zj+0duh+b1ppwPS8cjU89+LsE30a1eWgpJCEmHTmoU9yiMIEmQ="
  alipayPublicKey: "xxxxxxxxAAOCAQ8AMIIBCgKCAQEAj01pOUfFP8JmB6hT2tQJBn9rpM6hujeNtZJq9/BtQdFvUeUV3Vwu1bVRiMpFfGlNWLw1aM+vfObdLyNLnDjsWLx6b/c1hLio96Ic3vAHR4xLaG9y0R/PhXSwEWvQheua34oEM4oFmIzonuRALPQw1jwaybYGPKZkyX1IONdZ6LGAdzhXNNeCpShxslhuYh2N3PYXKQfBW27kCKFSugEqzRW1bydhU2ksNy6cDiums0iO92MuznMYNEmFgbNLd5Z1GdgPpJR1uKTlSq8OyaOxC+Ol/CAI9svBxLYgpEz93lJZRw5rz650AEDwG6heayJhYjoLo/VZSagyytS3m2SbTQIDAQAB"





wxPay:
  appID: 
  mchID: 
  appSecret: 
  key: 
  wxOAuth2RequestUrl: "https://open.weixin.qq.com/connect/oauth2/authorize"
  wxOAuth2CodeReturnUrl: 



pay:
  #支付入口url
  payurl: "http://192.168.3.143:56010/pay/pay-entry/"


#微信相关
weixin:
  oauth2RequestUrl: "https://open.weixin.qq.com/connect/oauth2/authorize"
  oauth2CodeReturnUrl: "http://175.7.167.148:56010/pay/wx-oauth-code-return"
  oauth2Token: "https://api.weixin.qq.com/sns/oauth2/access_token"